/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7srs;

import java.awt.GraphicsEnvironment;
import sm.srs.iu.Lienzo2DFinal;



/**
 *Clase correspondiente a una ventana interna de imágen
 * @author Sergi Ruiz Sánchez
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    //Atributos
    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    String []fuentesSistema = ge.getAvailableFontFamilyNames();

    
    

    public VentanaInterna() {
        initComponents();
    }

    /**
     * Obtener el lienzo asociado, para poder usarlo
     * @return Lienzo2DFinal lienzo
     */
    public Lienzo2DFinal getCanvas() {   
        return canvas;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas = new sm.srs.iu.Lienzo2DFinal();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.srs.iu.Lienzo2DFinal canvas;
    // End of variables declaration//GEN-END:variables
}
