/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.srs.iu;

import java.awt.Color;

/**
 *Clase donde le ponemos a cada uno de los botones de la lista de colores
 * (ya sea de borde o de relleno) su color correspondiente
 * @author Sergi Ruiz Sánchez
 */
public class PanelColor extends javax.swing.JPanel {

    /**
     * Constructor por defecto
     * @param color color que ese panel en concreto va a tener
     */
    public PanelColor(Color color) {
        initComponents();
        setColor(color);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color = new javax.swing.JButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Esta es la asociación real del color al botón
     * @param color color del botón
     */
void setColor(Color color){
    this.color.setBackground(color);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color;
    // End of variables declaration//GEN-END:variables
}
