/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.srs.iu;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *Panel para mostrar una imagen u otra asociada a los contrastes 
 * (normal,iluminado,oscurecido,negativo)
 * @author Sergi Ruiz Sánchez
 */
public class PanelContrast extends javax.swing.JPanel {

    /**
     * Constructor por defecto
     * @param label valor de etiqueta que le damos para saber qué imagen mostrar
     */
    public PanelContrast(String label) {
        initComponents();
        setBackground(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(25, 25));
        setLayout(new java.awt.BorderLayout());

        button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setPreferredSize(new java.awt.Dimension(25, 25));
        add(button, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para que dada una etiqueta le asocie un icono en el combobox
     * @param label etiqueta que le damos
     */
void setBackground(String label){
    
    if(label == "normal"){
        Image image = new ImageIcon(this.getClass().getResource("/icons/iconos/contraste.png")).getImage();
        this.button.setIcon(new ImageIcon(image));

    }
    
    else if(label == "iluminacion"){
        Image image = new ImageIcon(this.getClass().getResource("/icons/iconos/iluminar.png")).getImage();
        this.button.setIcon(new ImageIcon(image));

    }
    
    else if(label == "oscurecimiento"){
       Image image = new ImageIcon(this.getClass().getResource("/icons/iconos/oscurecer.png")).getImage();
       this.button.setIcon(new ImageIcon(image));
 
    }
    
    else{
      Image image = new ImageIcon(this.getClass().getResource("/icons/iconos/negativo.png")).getImage();
      this.button.setIcon(new ImageIcon(image));
  
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    // End of variables declaration//GEN-END:variables
}
